// Write a recursive decent algorithm for a java while statement, a Javas if statement , an 
// logical/mathematical expression based on the rules you created in your lexical analyzer, and an mathe- matical
// assignment statement, where statement may be an empty function. Supply the EBNF rule for each.

#include <stdio.h>
#include <ctype.h>

/* Global declarations */
/* Variables */
int nextToken;
void ifstmt(void);
void whilestmt(void);
void expr(void);
void term(void);
void factor(void);
void statement(void);
void error(void);
void lex(void);
void boolexpr(void);
void log(void);
void assign(void);

/* Token codes */
#define INT_LIT 10
#define IDENT 11
#define NOT_OP 12
#define ASSIGN_OP 20
#define ADD_OP 21
#define SUB_OP 22
#define MULT_OP 23
#define DIV_OP 24
#define LEFT_PAREN 25
#define RIGHT_PAREN 26
#define MOD_OP 27
#define IF_CODE 28
#define ELSE_CODE 29
#define WHILE_CODE 30
#define AND_OP 31
#define OR_OP 32
int main(){
    return 0;
}
/* ifstmt
 Parses strings in the language generated by the rule:
 <ifstmt> -> if (<boolexpr>) <statement>
 [else <statement>]
 */
void ifstmt(void) {
 if (nextToken != IF_CODE)
 	error();
 else {
	lex();
 	if (nextToken != LEFT_PAREN)
 		error();
 	else {
 		lex();
 		boolexpr();
 		if (nextToken != RIGHT_PAREN)
 			error();
 		else {
 			lex();
		 	statement();
 			if (nextToken == ELSE_CODE) {
 				lex();
 				statement();
 			}
 		}
 	}
 }
}
/* whilestmt
 Parses strings in the language generated by the rule:
 <whilestmt> -> while (<boolexpr>) <statement>
 */
void whilestmt(void) {
 if (nextToken != WHILE_CODE)
 	error();
 else {
	lex();
 	if (nextToken != LEFT_PAREN)
 		error();
 	else {
 		lex();
 		boolexpr();
 		if (nextToken != RIGHT_PAREN)
 			error();
 		else {
			lex();
			statement();
 			
 		}
 	}
 }
}

// /*
//  
//  <expr> -> <term> {(+ | -) <term>}
//  <term> -> <factor> {(* | / | % ) <factor>}
//  <factor> -> id | int_constant | ( <expr> )
//  <log> ->  {!} <expr> {(&&& | |||) <expr>}
//  <assign> -> id `=` <log>
 
//  LL Grammars
//  Read the input from left to right
//  Left Most Derivation
 
//  Left hand recursion direct or in direct
//  Must past pairwise disjointness test.

/* log
 Parses strings in the language generated by the rule:
 <log> ->  {!} <expr> {(&&& | |||) <expr>}
 */
void log(void) {
	 printf("Enter <log>\n");
     if (nextToken == NOT_OP){
        lex();
        expr();
     }else{
	    expr();
     }
    /* As long as the next token is &&& or |||, get
	 the next token and parse the next expr */
	 while (nextToken == AND_OP || nextToken == OR_OP) {
		 lex();
		 expr();
	 }
	 printf("Exit <log>\n");
}
 
/* assign
 Parses strings in the language generated by the rule:
 <assign> -> id `=` <log>
 */
void assign(void) {
	 printf("Enter <assign>\n");
	if (nextToken != IDENT){
		/* Get the next token */
		 error();
    }else{
        lex();
        if (nextToken != ASSIGN_OP){
            error();
        }else{
            lex();
            log();
        }
    }
	 printf("Exit <assign>\n");
}

/* expr
 Parses strings in the language generated by the rule:
 <expr> -> <term> {(+ | -) <term>} // reason for eBNF to elminate left hand recrussion
 <expr> -> <expr> + <term>
 */
void expr(void) {
	 printf("Enter <expr>\n");
	/* Parse the first term */
	 term();
	/* As long as the next token is + or -, get
	 the next token and parse the next term */
	 while (nextToken == ADD_OP || nextToken == SUB_OP) {
		 lex();
		 term();
	 }
	 printf("Exit <expr>\n");
}

/* term
 Parses strings in the language generated by the rule:
 <term> -> <factor> {(* | / | % ) <factor>}
 */
void term(void) {
	 printf("Enter <term>\n");
	/* Parse the first factor */
	 factor();
	/* As long as the next token is * or /, get the
	 next token and parse the next factor */
	 while (nextToken == MULT_OP || nextToken == DIV_OP || nextToken == MOD_OP) {
		 lex();
		 factor();
	 }
	 printf("Exit <term>\n");
}

/* factor
 Parses strings in the language generated by the rule:
 <factor> -> id | int_constant | ( <expr> )
 */
void factor(void) {
	 printf("Enter <factor>\n");
	/* Determine which RHS */
	 if (nextToken == IDENT || nextToken == INT_LIT)
		/* Get the next token */
		 lex();
		/* If the RHS is ( <expr> ), call lex to pass over the
		 left parenthesis, call expr, and check for the right
		 parenthesis */
	 else { if (nextToken == LEFT_PAREN) {
		 lex();
		 expr();
		 if (nextToken == RIGHT_PAREN)
		 	lex();
		 else
		 	error();
		 }
		/* It was not an id, an integer literal, or a left
		 parenthesis */
		 else
		 error();
	 }
	 printf("Exit <factor>\n");
}

void statement(void){

}
void error(void){

}
void lex(void){

}
void boolexpr(void){

}